namespace Edm.DocumentGenerator.Gateway.ExternalServices.EntitiesApprovalWorkflows.Actions.Contracts.Queries.GetAvailable;

public sealed record GetAvailableEntitiesApprovalWorkflowsActionsQueryExternal(string WorkflowId, string CurrentUserId, bool CurrentUserIsAdmin);
