namespace Edm.DocumentGenerators.Domain.Entities.Documents.ValueObjects.ApplicationEvents.Inheritors.DocumentGenerator.Events;

public abstract record DocumentGeneratorEventDocumentApplicationEvent : DocumentApplicationEvent;
