namespace Edm.DocumentGenerator.Gateway.ExternalServices.DocumentClassifier.RegistryRoles.Contracts.Roles.Types.Inheritors.Booleans;

public sealed record DocumentBooleanRegistryRoleTypeExternal : DocumentRegistryRoleTypeExternal;
