using Edm.DocumentGenerators.Domain.Markers;
using Edm.DocumentGenerators.GenericSubdomain;

namespace Edm.DocumentGenerators.Domain.Entities.Documents.ValueObjects.ApplicationEvents.Inheritors.EntitiesApprovalWorkflows.Requests.UpdateDocumentAuthor;

public sealed record UpdateDocumentAuthorEntitiesApprovalWorkflowsRequestDocumentApplicationEvent(Id<User> DocumentAuthorId)
    : EntitiesApprovalWorkflowsRequestDocumentApplicationEvent;
