namespace Edm.Document.Classifier.Domain.ValueObjects.Countries;

public static class CountryService
{
    private static readonly Dictionary<CountryCode, CountryInfo> Countries = new[]
    {
        new CountryInfo(CountryCode.None, null, "Не определено", null),
        new CountryInfo(CountryCode.Ab, "AB", "Республика Абхазия", "895"),
        new CountryInfo(CountryCode.Ad, "AD", "Княжество Андорра", "020"),
        new CountryInfo(CountryCode.Ae, "AE", "Объединенные Арабские Эмираты", "784"),
        new CountryInfo(CountryCode.Af, "AF", "Исламское Государство Афганистан", "004"),
        new CountryInfo(CountryCode.Ag, "AG", "Антигуа и Барбуда", "028"),
        new CountryInfo(CountryCode.Ai, "AI", "Ангилья", "660"),
        new CountryInfo(CountryCode.Al, "AL", "Республика Албания", "008"),
        new CountryInfo(CountryCode.Am, "AM", "Республика Армения", "051"),
        new CountryInfo(CountryCode.An, "AN", "Нидерландские Антилы", "530"),
        new CountryInfo(CountryCode.Ao, "AO", "Республика Ангола", "024"),
        new CountryInfo(CountryCode.Aq, "AQ", "Антарктида", "010"),
        new CountryInfo(CountryCode.Ar, "AR", "Аргентинская Республика", "032"),
        new CountryInfo(CountryCode.As, "AS", "Американское Самоа", "016"),
        new CountryInfo(CountryCode.At, "AT", "Австрийская Республика", "040"),
        new CountryInfo(CountryCode.Au, "AU", "Австралия", "036"),
        new CountryInfo(CountryCode.Aw, "AW", "Аруба", "533"),
        new CountryInfo(CountryCode.Ax, null, "Эландские острова", "248"),
        new CountryInfo(CountryCode.Az, "AZ", "Азербайджанская Республика", "031"),
        new CountryInfo(CountryCode.Ba, "BA", "Республика Босния и Герцеговина", "070"),
        new CountryInfo(CountryCode.Bb, "BB", "Барбадос", "052"),
        new CountryInfo(CountryCode.Bd, "BD", "Народная Республика Бангладеш", "050"),
        new CountryInfo(CountryCode.Be, "BE", "Королевство Бельгии", "056"),
        new CountryInfo(CountryCode.Bf, "BF", "Буркина-Фасо", "854"),
        new CountryInfo(CountryCode.Bg, "BG", "Республика Болгария", "100"),
        new CountryInfo(CountryCode.Bh, "BH", "Государство Бахрейн", "048"),
        new CountryInfo(CountryCode.Bi, "BI", "Республика Бурунди", "108"),
        new CountryInfo(CountryCode.Bj, "BJ", "Республика Бенин", "204"),
        new CountryInfo(CountryCode.Bm, "BM", "Бермуды", "060"),
        new CountryInfo(CountryCode.Bn, "BN", "Бруней-Даруссалам", "096"),
        new CountryInfo(CountryCode.Bo, "BO", "Республика Боливия", "068"),
        new CountryInfo(CountryCode.Bq, null, "Бонайре, Саба и Синт-Эстатиус", "535"),
        new CountryInfo(CountryCode.Br, "BR", "Федеративная Республика Бразилия", "076"),
        new CountryInfo(CountryCode.Bs, "BS", "Содружество Багамы", "044"),
        new CountryInfo(CountryCode.Bt, "BT", "Королевство Бутан", "064"),
        new CountryInfo(CountryCode.Bv, "BV", "Остров Буве", "074"),
        new CountryInfo(CountryCode.Bw, "BW", "Республика Ботсвана", "072"),
        new CountryInfo(CountryCode.By, "BY", "Республика Беларусь", "112"),
        new CountryInfo(CountryCode.Bz, "BZ", "Белиз", "084"),
        new CountryInfo(CountryCode.Ca, "CA", "Канада", "124"),
        new CountryInfo(CountryCode.Cc, "CC", "Кокосовые (Килинг) острова", "166"),
        new CountryInfo(CountryCode.Cd, "CD", "Демократическая Республика Конго", "180"),
        new CountryInfo(CountryCode.Cf, "CF", "Центрально-Африканская Республика", "140"),
        new CountryInfo(CountryCode.Cg, "CG", "Республика Конго", "178"),
        new CountryInfo(CountryCode.Ch, "CH", "Швейцарская Конфедерация", "756"),
        new CountryInfo(CountryCode.Ci, "CI", "Республика Кот д'Ивуар", "384"),
        new CountryInfo(CountryCode.Ck, "CK", "Острова Кука", "184"),
        new CountryInfo(CountryCode.Cl, "CL", "Республика Чили", "152"),
        new CountryInfo(CountryCode.Cm, "CM", "Республика Камерун", "120"),
        new CountryInfo(CountryCode.Cn, "CN", "Китайская Народная Республика", "156"),
        new CountryInfo(CountryCode.Co, "CO", "Республика Колумбия", "170"),
        new CountryInfo(CountryCode.Cr, "CR", "Республика Коста - Рика", "188"),
        new CountryInfo(CountryCode.Cu, "CU", "Республика Куба", "192"),
        new CountryInfo(CountryCode.Cv, "CV", "Республика Кабо - Верде", "132"),
        new CountryInfo(CountryCode.Cx, "CX", "Остров Рождества", "162"),
        new CountryInfo(CountryCode.Cy, "CY", "Республика Кипр", "196"),
        new CountryInfo(CountryCode.Cz, "CZ", "Чешская Республика", "203"),
        new CountryInfo(CountryCode.De, "DE", "Федеративная Республика Германия", "276"),
        new CountryInfo(CountryCode.Dj, "DJ", "Республика Джибути", "262"),
        new CountryInfo(CountryCode.Dk, "DK", "Королевство Дания", "208"),
        new CountryInfo(CountryCode.Dm, "DM", "Содружество Доминики", "212"),
        new CountryInfo(CountryCode.Do, "DO", "Доминиканская Республика", "214"),
        new CountryInfo(CountryCode.Dz, "DZ", "Алжирская Народная Демократическая Республика", "012"),
        new CountryInfo(CountryCode.Eaeu, "EAEU", "Евразийский экономический союз", null),
        new CountryInfo(CountryCode.Ec, "EC", "Республика Эквадор", "218"),
        new CountryInfo(CountryCode.Ee, "EE", "Эстонская Республика", "233"),
        new CountryInfo(CountryCode.Eg, "EG", "Арабская Республика Египет", "818"),
        new CountryInfo(CountryCode.Eh, "EH", "Западная Сахара", "732"),
        new CountryInfo(CountryCode.Er, "ER", "Государство Эритрея", "232"),
        new CountryInfo(CountryCode.Es, "ES", "Королевство Испания", "724"),
        new CountryInfo(CountryCode.Et, "ET", "Федеративная Демократическая Республика Эфиопия", "231"),
        new CountryInfo(CountryCode.Eu, "EU", "Европейский союз", null),
        new CountryInfo(CountryCode.Fi, "FI", "Финляндская Республика", "246"),
        new CountryInfo(CountryCode.Fj, "FJ", "Республика Фиджи", "242"),
        new CountryInfo(CountryCode.Fk, "FK", "Фолклендские острова (Мальвинские)", "238"),
        new CountryInfo(CountryCode.Fm, "FM", "Федеративные штаты Микронезии", "583"),
        new CountryInfo(CountryCode.Fo, "FO", "Фарерские острова", "234"),
        new CountryInfo(CountryCode.Fr, "FR", "Французская Республика", "250"),
        new CountryInfo(CountryCode.Ga, "GA", "Габонская Республика", "266"),
        new CountryInfo(CountryCode.Gb, "GB", "Соединенное Королевство Великобритании и Северной Ирландии", "826"),
        new CountryInfo(CountryCode.Gd, "GD", "Гренада", "308"),
        new CountryInfo(CountryCode.Ge, "GE", "Грузия", "268"),
        new CountryInfo(CountryCode.Gf, "GF", "Французская Гвиана", "254"),
        new CountryInfo(CountryCode.Gg, null, "Гернси", "831"),
        new CountryInfo(CountryCode.Gh, "GH", "Республика Гана", "288"),
        new CountryInfo(CountryCode.Gi, "GI", "Гибралтар", "292"),
        new CountryInfo(CountryCode.Gl, "GL", "Гренландия", "304"),
        new CountryInfo(CountryCode.Gm, "GM", "Республика Гамбия", "270"),
        new CountryInfo(CountryCode.Gn, "GN", "Гвинейская Республика", "324"),
        new CountryInfo(CountryCode.Gp, "GP", "Гваделупа", "312"),
        new CountryInfo(CountryCode.Gq, "GQ", "Республика Экваториальная Гвинея", "226"),
        new CountryInfo(CountryCode.Gr, "GR", "Греческая Республика", "300"),
        new CountryInfo(CountryCode.Gs, "GS", "Южная Джорджия и Южные Сандвичевы острова", "239"),
        new CountryInfo(CountryCode.Gt, "GT", "Республика Гватемала", "320"),
        new CountryInfo(CountryCode.Gu, "GU", "Гуам", "316"),
        new CountryInfo(CountryCode.Gw, "GW", "Республика Гвинея - Бисау", "624"),
        new CountryInfo(CountryCode.Gy, "GY", "Республика Гайана", "328"),
        new CountryInfo(CountryCode.Hk, "HK", "Гонконг", "344"),
        new CountryInfo(CountryCode.Hm, "HM", "Остров Херд и острова Макдональд", "334"),
        new CountryInfo(CountryCode.Hn, "HN", "Республика Гондурас", "340"),
        new CountryInfo(CountryCode.Hr, "HR", "Республика Хорватия", "191"),
        new CountryInfo(CountryCode.Ht, "HT", "Республика Гаити", "332"),
        new CountryInfo(CountryCode.Hu, "HU", "Венгерская Республика", "348"),
        new CountryInfo(CountryCode.Id, "ID", "Республика Индонезия", "360"),
        new CountryInfo(CountryCode.Ie, "IE", "Ирландия", "372"),
        new CountryInfo(CountryCode.Il, "IL", "Государство Израиль", "376"),
        new CountryInfo(CountryCode.In, "IN", "Республика Индия", "356"),
        new CountryInfo(CountryCode.Io, "IO", "Британская территория в Индийском океане", "086"),
        new CountryInfo(CountryCode.Iq, "IQ", "Республика Ирак", "368"),
        new CountryInfo(CountryCode.Ir, "IR", "Исламская Республика Иран", "364"),
        new CountryInfo(CountryCode.Is, "IS", "Республика Исландия", "352"),
        new CountryInfo(CountryCode.It, "IT", "Итальянская Республика", "380"),
        new CountryInfo(CountryCode.Je, null, "Джерси", "832"),
        new CountryInfo(CountryCode.Jm, "JM", "Ямайка", "388"),
        new CountryInfo(CountryCode.Jo, "JO", "Иорданское Хашимитское Королевство", "400"),
        new CountryInfo(CountryCode.Jp, "JP", "Япония", "392"),
        new CountryInfo(CountryCode.Ke, "KE", "Республика Кения", "404"),
        new CountryInfo(CountryCode.Kg, "KG", "Киргизская Республика", "417"),
        new CountryInfo(CountryCode.Kh, "KH", "Королевство Камбоджа", "116"),
        new CountryInfo(CountryCode.Ki, "KI", "Кирибати", "296"),
        new CountryInfo(CountryCode.Km, "KM", "Исламская Федеральная Республика Коморы", "174"),
        new CountryInfo(CountryCode.Kn, "KN", "Сент-Китс и Невис", "659"),
        new CountryInfo(CountryCode.Kp, "KP", "Корейская Народно - Демократическая Республика", "408"),
        new CountryInfo(CountryCode.Kr, "KR", "Республика Корея", "410"),
        new CountryInfo(CountryCode.Kw, "KW", "Государство Кувейт", "414"),
        new CountryInfo(CountryCode.Ky, "KY", "Острова Кайман", "136"),
        new CountryInfo(CountryCode.Kz, "KZ", "Республика Казахстан", "398"),
        new CountryInfo(CountryCode.La, "LA", "Лаос", "418"),
        new CountryInfo(CountryCode.Lb, "LB", "Ливанская Республика", "422"),
        new CountryInfo(CountryCode.Lc, "LC", "Сент-Люсия", "662"),
        new CountryInfo(CountryCode.Li, "LI", "Княжество Лихтенштейн", "438"),
        new CountryInfo(CountryCode.Lk, "LK", "Демократическая Социалистическая Республика Шри - Ланка", "144"),
        new CountryInfo(CountryCode.Lr, "LR", "Республика Либерия", "430"),
        new CountryInfo(CountryCode.Ls, "LS", "Королевство Лесото", "426"),
        new CountryInfo(CountryCode.Lt, "LT", "Литовская Республика", "440"),
        new CountryInfo(CountryCode.Lu, "LU", "Великое Герцогство Люксембург", "442"),
        new CountryInfo(CountryCode.Lv, "LV", "Латвийская Республика", "428"),
        new CountryInfo(CountryCode.Ly, "LY", "Социалистическая Народная Ливийская Арабская Джамахирия", "434"),
        new CountryInfo(CountryCode.Ma, "MA", "Королевство Марокко", "504"),
        new CountryInfo(CountryCode.Mc, "MC", "Княжество Монако", "492"),
        new CountryInfo(CountryCode.Md, "MD", "Республика Молдова", "498"),
        new CountryInfo(CountryCode.Me, "ME", "Черногория", "499"),
        new CountryInfo(CountryCode.Mf, null, "Сен-Мартен", "663"),
        new CountryInfo(CountryCode.Mg, "MG", "Республика Мадагаскар", "450"),
        new CountryInfo(CountryCode.Mh, "MH", "Республика Маршалловы Острова", "584"),
        new CountryInfo(CountryCode.Mk, "MK", "Бывшая Югославская Республика Македония", "807"),
        new CountryInfo(CountryCode.Ml, "ML", "Республика Мали", "466"),
        new CountryInfo(CountryCode.Mm, "MM", "Союз Мьянма", "104"),
        new CountryInfo(CountryCode.Mn, "MN", "Монголия", "496"),
        new CountryInfo(CountryCode.Mo, "MO", "Макао", "446"),
        new CountryInfo(CountryCode.Mp, "MP", "Содружество Северных Марианских островов", "580"),
        new CountryInfo(CountryCode.Mq, "MQ", "Мартиника", "474"),
        new CountryInfo(CountryCode.Mr, "MR", "Исламская Республика Мавритания", "478"),
        new CountryInfo(CountryCode.Ms, "MS", "Монтсеррат", "500"),
        new CountryInfo(CountryCode.Mt, "MT", "Республика Мальта", "470"),
        new CountryInfo(CountryCode.Mu, "MU", "Республика Маврикий", "480"),
        new CountryInfo(CountryCode.Mv, "MV", "Мальдивская Республика", "462"),
        new CountryInfo(CountryCode.Mw, "MW", "Республика Малави", "454"),
        new CountryInfo(CountryCode.Mx, "MX", "Мексиканские Соединенные Штаты", "484"),
        new CountryInfo(CountryCode.My, "MY", "Малайзия", "458"),
        new CountryInfo(CountryCode.Mz, "MZ", "Республика Мозамбик", "508"),
        new CountryInfo(CountryCode.Na, "NA", "Республика Намибия", "516"),
        new CountryInfo(CountryCode.Nc, "NC", "Новая Каледония", "540"),
        new CountryInfo(CountryCode.Ne, "NE", "Республика Нигер", "562"),
        new CountryInfo(CountryCode.Nf, "NF", "Остров Норфолк", "574"),
        new CountryInfo(CountryCode.Ng, "NG", "Федеративная Республика Нигерия", "566"),
        new CountryInfo(CountryCode.Ni, "NI", "Республика Никарагуа", "558"),
        new CountryInfo(CountryCode.Nl, "NL", "Королевство Нидерландов", "528"),
        new CountryInfo(CountryCode.No, "NO", "Королевство Норвегия", "578"),
        new CountryInfo(CountryCode.Np, "NP", "Королевство Непал", "524"),
        new CountryInfo(CountryCode.Nr, "NR", "Республика Науру", "520"),
        new CountryInfo(CountryCode.Nu, "NU", "Ниуэ", "570"),
        new CountryInfo(CountryCode.Nz, "NZ", "Новая Зеландия", "554"),
        new CountryInfo(CountryCode.Om, "OM", "Султанат Оман", "512"),
        new CountryInfo(CountryCode.Os, "OS", "Республика Южная Осетия", "896"),
        new CountryInfo(CountryCode.Pa, "PA", "Республика Панама", "591"),
        new CountryInfo(CountryCode.Pe, "PE", "Республика Перу", "604"),
        new CountryInfo(CountryCode.Pf, "PF", "Французская Полинезия", "258"),
        new CountryInfo(CountryCode.Pg, "PG", "Независимое Государство Папуа Новая Гвинея", "598"),
        new CountryInfo(CountryCode.Ph, "PH", "Республика Филиппины", "608"),
        new CountryInfo(CountryCode.Pk, "PK", "Исламская Республика Пакистан", "586"),
        new CountryInfo(CountryCode.Pl, "PL", "Республика Польша", "616"),
        new CountryInfo(CountryCode.Pm, "PM", "Сент-Пьер и Микелон", "666"),
        new CountryInfo(CountryCode.Pn, "PN", "Питкерн", "612"),
        new CountryInfo(CountryCode.Pr, "PR", "Пуэрто-Рико", "630"),
        new CountryInfo(CountryCode.Ps, "PS", "Государство Палестина", "275"),
        new CountryInfo(CountryCode.Pt, "PT", "Португальская Республика", "620"),
        new CountryInfo(CountryCode.Pw, "PW", "Республика Палау", "585"),
        new CountryInfo(CountryCode.Py, "PY", "Республика Парагвай", "600"),
        new CountryInfo(CountryCode.Qa, "QA", "Государство Катар", "634"),
        new CountryInfo(CountryCode.Re, "RE", "Реюньон", "638"),
        new CountryInfo(CountryCode.Ro, "RO", "Румыния", "642"),
        new CountryInfo(CountryCode.Rs, "RS", "Республика Сербия", "688"),
        new CountryInfo(CountryCode.Ru, "RU", "Российская Федерация", "643"),
        new CountryInfo(CountryCode.Rw, "RW", "Руандийская Республика", "646"),
        new CountryInfo(CountryCode.Sa, "SA", "Королевство Саудовская Аравия", "682"),
        new CountryInfo(CountryCode.Sb, "SB", "Соломоновы острова", "090"),
        new CountryInfo(CountryCode.Sc, "SC", "Республика Сейшелы", "690"),
        new CountryInfo(CountryCode.Sd, "SD", "Республика Судан", "729"),
        new CountryInfo(CountryCode.Se, "SE", "Королевство Швеция", "752"),
        new CountryInfo(CountryCode.Sg, "SG", "Республика Сингапур", "702"),
        new CountryInfo(CountryCode.Sh, "SH", "Святая Елена, Остров вознесения, Тристан-да-Кунья", "654"),
        new CountryInfo(CountryCode.Si, "SI", "Республика Словения", "705"),
        new CountryInfo(CountryCode.Sj, "SJ", "Шпицберген и Ян Майен", "744"),
        new CountryInfo(CountryCode.Sk, "SK", "Словацкая Республика", "703"),
        new CountryInfo(CountryCode.Sl, "SL", "Республика Сьерра - Леоне", "694"),
        new CountryInfo(CountryCode.Sm, "SM", "Республика Сан - Марино", "674"),
        new CountryInfo(CountryCode.Sn, "SN", "Республика Сенегал", "686"),
        new CountryInfo(CountryCode.So, "SO", "Федеративная Республика Сомали", "706"),
        new CountryInfo(CountryCode.Sr, "SR", "Республика Суринам", "740"),
        new CountryInfo(CountryCode.Ss, null, "Южный Судан", "728"),
        new CountryInfo(CountryCode.St, "ST", "Демократическая Республика Сан - Томе и Принсипи", "678"),
        new CountryInfo(CountryCode.Sv, "SV", "Республика Эль - Сальвадор", "222"),
        new CountryInfo(CountryCode.Sy, "SY", "Сирийская Арабская Республика", "760"),
        new CountryInfo(CountryCode.Sz, "SZ", "Королевство Свазиленд", "748"),
        new CountryInfo(CountryCode.Tc, "TC", "Острова Теркс и Кайкос", "796"),
        new CountryInfo(CountryCode.Td, "TD", "Республика Чад", "148"),
        new CountryInfo(CountryCode.Tf, "TF", "Французские Южные территории", "260"),
        new CountryInfo(CountryCode.Tg, "TG", "Тоголезская Республика", "768"),
        new CountryInfo(CountryCode.Th, "TH", "Королевство Таиланд", "764"),
        new CountryInfo(CountryCode.Tj, "TJ", "Республика Таджикистан", "762"),
        new CountryInfo(CountryCode.Tk, "TK", "Токелау", "772"),
        new CountryInfo(CountryCode.Tl, "TP", "Восточный Тимор", "626"),
        new CountryInfo(CountryCode.Tm, "TM", "Туркменистан", "795"),
        new CountryInfo(CountryCode.Tn, "TN", "Тунисская Республика", "788"),
        new CountryInfo(CountryCode.To, "TO", "Королевство Тонга", "776"),
        new CountryInfo(CountryCode.Tr, "TR", "Турецкая Республика", "792"),
        new CountryInfo(CountryCode.Tt, "TT", "Республика Тринидад и Тобаго", "780"),
        new CountryInfo(CountryCode.Tv, "TV", "Тувалу", "798"),
        new CountryInfo(CountryCode.Tw, "TW", "Тайвань (Китай)", "158"),
        new CountryInfo(CountryCode.Tz, "TZ", "Объединенная Республика Танзания", "834"),
        new CountryInfo(CountryCode.Ua, "UA", "Украина", "804"),
        new CountryInfo(CountryCode.Ug, "UG", "Республика Уганда", "800"),
        new CountryInfo(CountryCode.Um, "UM", "Малые Тихоокеанские отдаленные острова Соединенных Штатов", "581"),
        new CountryInfo(CountryCode.Us, "US", "Соединенные Штаты Америки", "840"),
        new CountryInfo(CountryCode.Uy, "UY", "Восточная Республика Уругвай", "858"),
        new CountryInfo(CountryCode.Uz, "UZ", "Республика Узбекистан", "860"),
        new CountryInfo(CountryCode.Va, "VA", "Папский Престол (Государство — город Ватикан)", "336"),
        new CountryInfo(CountryCode.Vc, "VC", "Сент-Винсент и Гренадины", "670"),
        new CountryInfo(CountryCode.Ve, "VE", "Республика Венесуэла", "862"),
        new CountryInfo(CountryCode.Vg, "VG", "Британские Виргинские острова", "092"),
        new CountryInfo(CountryCode.Vi, "VI", "Виргинские острова Соединенных Штатов", "850"),
        new CountryInfo(CountryCode.Vn, "VN", "Социалистическая Республика Вьетнам", "704"),
        new CountryInfo(CountryCode.Vu, "VU", "Республика Вануату", "548"),
        new CountryInfo(CountryCode.Wf, null, "Уоллис и Футуна", "876"),
        new CountryInfo(CountryCode.Ws, "WS", "Независимое Государство Западное Самоа", "882"),
        new CountryInfo(CountryCode.Ye, "YE", "Йеменская Республика", "887"),
        new CountryInfo(CountryCode.Yt, "YT", "Майотта", "175"),
        new CountryInfo(CountryCode.Yu, "YU", "Союзная Республика Югославия", null),
        new CountryInfo(CountryCode.Za, "ZA", "Южно - Африканская Республика", "710"),
        new CountryInfo(CountryCode.Zm, "ZM", "Республика Замбия", "894"),
        new CountryInfo(CountryCode.Zw, "ZW", "Республика Зимбабве", "716")
    }.ToDictionary((Func<CountryInfo, CountryCode>)(r => r.Code));

    private static readonly Dictionary<string, CountryInfo> CountriesMetazon = Countries
        .Where(c => !string.IsNullOrEmpty(c.Value.IsoCodeAlpha2))
        .ToDictionary(
            (Func<KeyValuePair<CountryCode, CountryInfo>, string>)(x => x.Value.IsoCodeAlpha2!),
            (Func<KeyValuePair<CountryCode, CountryInfo>, CountryInfo>)(x => x.Value));

    public static CountryInfo Get(CountryCode input)
    {
        return Countries[input];
    }

    public static IReadOnlyCollection<CountryInfo> GetAll()
    {
        return Countries.Values.ToArray<CountryInfo>();
    }

    public static CountryInfo? SearchByIsoCodeAlpha2(string? country)
    {
        return string.IsNullOrEmpty(country) || !CountriesMetazon.TryGetValue(country, out var countryInfo) ? null : countryInfo;
    }
}
