namespace Edm.DocumentGenerator.Gateway.ExternalServices.DocumentClassifier.RegistryRoles.Contracts.DocumentsAttributes.AttributesTypes.Inheritors;

public sealed class DocumentAttachmentAttributeTypeExternal : DocumentAttributeTypeExternal;
