using Edm.DocumentGenerators.ExternalServices.EntitiesApprovalRules.SupportRequestApprovalRules.Templates;

namespace Edm.DocumentGenerators.ExternalServices.EntitiesApprovalRules.SupportRequestApprovalRules;

public sealed record SupportRequestApprovalRuleExternal(SupportRequestTemplateExternal[] Templates);
