namespace Edm.DocumentGenerators.Application.Documents.Commands.Update.Contracts.Parameters.StatusChanges.StatusesTransitionsParametersValues;

public abstract class DocumentStatusTransitionParameterValueInternal
{
}
