namespace Edm.DocumentGenerators.Domain.Entities.Documents.ValueObjects.ApplicationEvents.Inheritors.EntitiesSigningWorkflows.Requests;

public abstract record EntitiesSigningWorkflowsRequestDocumentApplicationEvent : DocumentApplicationEvent;
