namespace Edm.DocumentGenerators.Domain.Entities.Documents.ValueObjects.ApplicationEvents.Inheritors.DocumentNotifier.Requests;

public abstract record DocumentNotifierRequestDocumentApplicationEvent : DocumentApplicationEvent;
