namespace Edm.DocumentGenerators.Domain.Entities.Documents.ValueObjects.ApplicationEvents.Inheritors.DocumentGenerator.Events.DocumentChanged;

public sealed record DocumentChangedDocumentGeneratorEventDocumentApplicationEvent : DocumentGeneratorEventDocumentApplicationEvent;
