namespace Edm.Document.Classifier.Application.DocumentRegistryRoles.Queries.GetAllDomains.Contracts.Domains.Roles.Types.Inheritors.Booleans;

public sealed record BooleanDocumentRegistryRoleTypeInternal : DocumentRegistryRoleTypeInternal;
