using MediatR;

namespace Edm.DocumentGenerators.Application.DocumentsStatusesParameters.Queries.GetDefaultParametersByStatusType.Contracts;

public sealed class GetDefaultDocumentsStatusesParametersByStatusTypeQueryInternal
    : IRequest<GetDefaultDocumentsStatusesParametersByStatusTypeQueryInternalResponse>
{
}
