namespace Edm.DocumentGenerator.Gateway.ExternalServices.Entities.Signing.Workflows.Actions.Services.GetDocumentsToSign.Contracts.DocumentsToSign;

public sealed record SigningWorkflowDocumentToSignDto(Guid DocumentAttachmentId);
