namespace Edm.DocumentGenerator.Gateway.ExternalServices.DocumentClassifier.RegistryRoles.Contracts.Roles.Types.Inheritors.Strings;

public sealed record DocumentStringRegistryRoleTypeExternal : DocumentRegistryRoleTypeExternal;
