using Edm.DocumentGenerators.Domain.Markers;
using Edm.DocumentGenerators.GenericSubdomain;

namespace Edm.DocumentGenerators.Domain.Entities.Documents.ValueObjects.ApplicationEvents.Inheritors.EntitiesSigningWorkflows.Requests.UpdateExecutor;

public sealed record UpdateExecutorEntitiesSigningWorkflowsRequestDocumentApplicationEvent(Id<User> ExecutorId) : EntitiesSigningWorkflowsRequestDocumentApplicationEvent;
