namespace Edm.DocumentGenerators.Domain.Entities.Documents.ValueObjects.ApplicationEvents.Inheritors.EntitiesApprovalWorkflows.Requests;

public abstract record EntitiesApprovalWorkflowsRequestDocumentApplicationEvent : DocumentApplicationEvent;
