using Edm.Document.Searcher.ExternalServices.EntitiesSigningWorkflows.Details.Contracts.Queries.GetWorkflows.Workflows;

namespace Edm.Document.Searcher.ExternalServices.EntitiesSigningWorkflows.Details.Contracts.Queries.GetWorkflows;

public sealed record GetWorkflowsSigningWorkflowDetailsQueryResponseExternal(SigningWorkflowExternal[] Workflows);
