namespace Edm.DocumentGenerator.Gateway.Core.DocumentsWorkflows.Signing.Actions.Commands.WithdrawByContractor.Contracts;

public sealed class WithdrawByContractorDocumentWorkflowSigningActionCommandBffResponse
{
}
